#ifndef EMLIFE_EMLEXCEPT_H
#define EMLIFE_EMLEXCEPT_H
enum Errors {
	SUCCESS                       = 0,
	FAILED_TO_SPECIFY_ENDPOINT    = 1,
	FAILED_TO_SPECIFY_ALL_DIAMOND = 2
};
#endif //EMLIFE_EMLEXCEPT_H
